### PR TITLE
587 - Fix for dropdown keyboard accessibility v.2

### LINKED ISSUE #587: Dropdowns are not keyboard accessible
**Bug Description**
The Get Started, Community and More dropdowns are not keyboard accessible.

**Steps to Reproduce**
Scenario 1:-
1. Go to [thenewboston](https://www.thenewboston.com/)
2. Click on Get Started or any other dropdown text.
3. Press Tab Key

Scenario2:-
1. Go to [thenewboston](https://www.thenewboston.com/)
2. Press tab key until you are over any of the dropdown text, press enter/space and press tab key again.

**Expected behavior**
The list of items of dropdown should get focus

**Actual behavior**
The list items do not get focused

**Screenshots/Recordings**
[Recording](https://drive.google.com/file/d/14BC82nRqS6t_F9aH7C6Ke_SS8JpjiYAP/view?usp=sharing)

**OS and Browser**
 - OS: [e.g. macOS]
 - Browser [e.g. Chrome, Firefox, Safari]

**Additional context**
Also multiple dropdowns can be opened at the same time using enter/space. This can be also be corrected in this same issue.

### PR DESCRIPTION
**Pull request by angle943**
closes #587

### CODE REVIEW

File: src/containers/TopNav/TopNavButton/index.tsx [hunk 1]
```diff
@@ -2,20 +2,20 @@ import React, {FC} from 'react';
...
 interface ComponentProps {
   buttonText: string;
   className?: string;
   toUrl: string;
 }
 
-const TopNavText: FC<ComponentProps> = ({buttonText, className, toUrl}) => {
+const TopNavButton: FC<ComponentProps> = ({buttonText, className, toUrl}) => {
   return (
     <Link to={toUrl}>
```
Comment (thesanjeevsharma) [inline src/containers/TopNav/TopNavButton/index.tsx:15]: I think we should add `tabIndex={-1}` here on the Link.

Right now, both `a` and `button` elements are focusable, this causes me to focus two times on 'Create Account' and 'Sign In' each.
