### PR TITLE
Reuse avatar component in SlideUpAccountDetails

### LINKED ISSUE #1051: [Leaderboard] Slide up account details shifts around when initially loaded
**Bug Description**
When using mobile devices, the slide up account details seems to shift around when it is initially loaded.

**Steps to Reproduce**
1. With a mobile device, head to the leaderboard
2. Click on a profile
3. View that the details is slightly shifted around when initially loaded

**Expected behavior**
Content shouldn't shift around when initially loaded

**Actual behavior**
Content shifts slightly to the right when initially loaded

**Screenshots/Recordings**
leaderboard_slide_up

**OS and Browser**
 - OS: Safari, Mac

**Additional context**

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #1051 

Acc No: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

### CODE REVIEW

File: src/containers/SlideUpAccountDetails/index.tsx [hunk 1]
```diff
@@ -28,7 +28,12 @@ const SlideUpAccountDetails: FC<ComponentProps> = ({account_number, close, githu
     <SlideUp className="SlideUpAccountDetails__SlideUp" close={close}>
       <div className="SlideUpAccountDetails__inner-wrapper">
         <div>
-          <img className="SlideUpAccountDetails__user-avatar" src={github_avatar_url} alt={github_username} />
+          <Avatar
+            alt={github_username}
+            className="SlideUpAccountDetails__user-avatar"
```
Comment (thesanjeevsharma) [inline src/containers/SlideUpAccountDetails/index.tsx:33]: @jamessspanggg If you have deleted the css, then there's no need of passing the class name.

**Review by thesanjeevsharma — APPROVED** [review]
